### ISSUE TITLE
Cannot load ope-rb/native

### ISSUE THREAD

**Issue by tonyo** [louismullie/ope-rb#2]
Hi, 

I would like to try this gem out, but when I do `require 'ope-rb'` in IRB a `LoadError` is thrown:

```
2.1.5 :001 > require 'ope-rb'
LoadError: cannot load such file -- ope-rb/native
        from /home/tonyo/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/tonyo/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/tonyo/.rvm/gems/ruby-2.1.5/gems/ope-rb-0.0.1/lib/ope-rb.rb:1:in `<top (required)>'
        from /home/tonyo/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /home/tonyo/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /home/tonyo/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from /home/tonyo/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

I use RVM with Ruby 2.1.5.

**Comment by jtdaugherty** [comment]
I've also encountered this problem with Ruby 2.2.3 on OS X:
```
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ope-rb/native (LoadError)
        from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/ope-rb-0.0.1/lib/ope-rb.rb:1:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from test.rb:3:in `<main>'
```
Here are the contents of the installed gem:
```
user@host:/usr/local/lib/ruby/gems/2.2.0/gems/ope-rb-0.0.1$ find . -type f
./ext/ope/.RUBYARCHDIR.-.ope.time
./ext/ope/extconf.rb
./ext/ope/Makefile
./ext/ope/native.bundle
./ext/ope/native.c
./ext/ope/native.o
./lib/ope/native.bundle
./lib/ope-rb/crypto.rb
./lib/ope-rb/errors.rb
./lib/ope-rb/hgd.rb
./lib/ope-rb/prng.rb
./lib/ope-rb/version.rb
./lib/ope-rb.rb
```

**Comment by louismullie** [comment]
Native part is a work in progress and can be ditched all together, unless somebody wants to finish it (which would be very tedious because of C's lack of support for Big Ints). If someone wants to make a PR to scrap that part and just keep the Ruby code that would be great, and fix this error.
