### ISSUE TITLE
Some plaintexts trigger HGD parameter exception

### ISSUE THREAD

**Issue by jtdaugherty** [louismullie/ope-rb#3]
I get this error,
```
/.../ope-rb/lib/ope-rb.rb:40:in `sample_hgd': Corrupt HGD parameters (OPE::Errors::HGDParameterError)
        from /.../ope-rb/lib/ope-rb.rb:113:in `encrypt_recurse'
        from /.../ope-rb/lib/ope-rb.rb:118:in `encrypt_recurse'
        ... (repeated encrypt_recurse lines)
```
when running this toy program:
```
#!/usr/bin/env ruby

require 'ope-rb'
require 'securerandom'

key = SecureRandom.random_bytes(OPE::Cipher::OPE_KEY_SIZE/8)
cipher = OPE::Cipher.new(key)

val = 19292900982200820
val_ct = cipher.encrypt(val)
```

**Comment by jtdaugherty** [comment]
For what it's worth, I've found that values up to and including `2 ** 53` do not cause this behavior, but anything larger (such as `(2 ** 53) + 1`) does.

**Comment by louismullie** [comment]
It is pretty clear to me that this is a precision error here. 2^53 is a 64-bit double. Not sure why this would occur since Ruby is supposed to guarantee arbitrary precision numbers. 

What are you trying to do with numbers that big?

**Comment by jtdaugherty** [comment]
I'm not really trying to do anything specific aside from test the library with values up to `2 ** 64`.  If the behavior isn't indicative of a bug, then documentation explaining the expected range of inputs (and why) would be very helpful for understanding the library's limitations (planned or otherwise).

**Comment by mochetts** [comment]
I faced the same problem. The reason why we need to encrypt large numbers is because that large number represents a concatenation of `orders` of each letter of the string. 
So if:
```ruby
"a".ord = 97
"b".ord = 98
```
The calculated order of the string "ab" would be 9798.

We want to do this mapping of char -> ord in order to encrypt this mapping and then be able to "sort" by these encrypted fields.

For example, if we wanted to encrypt the first and last name of the user, but then in the app we wanted to sort by these fields, I could easily call `desc(:first_name_encrypted)` and the outcome would be the same as sorting by the decrypted first_name.
